USE [master]
GO
/****** Object:  Database [LSI_Export]    Script Date: 04.08.2022 17:24:59 ******/
CREATE DATABASE [LSI_Export]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LSI_Export', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\LSI_Export.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'LSI_Export_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.SQLEXPRESS\MSSQL\DATA\LSI_Export_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [LSI_Export] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LSI_Export].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [LSI_Export] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [LSI_Export] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [LSI_Export] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [LSI_Export] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [LSI_Export] SET ARITHABORT OFF 
GO
ALTER DATABASE [LSI_Export] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [LSI_Export] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [LSI_Export] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [LSI_Export] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [LSI_Export] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [LSI_Export] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [LSI_Export] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [LSI_Export] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [LSI_Export] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [LSI_Export] SET  DISABLE_BROKER 
GO
ALTER DATABASE [LSI_Export] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [LSI_Export] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [LSI_Export] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [LSI_Export] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [LSI_Export] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [LSI_Export] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [LSI_Export] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [LSI_Export] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [LSI_Export] SET  MULTI_USER 
GO
ALTER DATABASE [LSI_Export] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [LSI_Export] SET DB_CHAINING OFF 
GO
ALTER DATABASE [LSI_Export] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [LSI_Export] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [LSI_Export]
GO
/****** Object:  Table [dbo].[EXPORT]    Script Date: 04.08.2022 17:24:59 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EXPORT](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[EXPORT_NAME] [nchar](255) NULL,
	[EXPORT_DATETIME] [datetime] NULL,
	[EXPORT_USER] [nchar](255) NULL,
	[EXPORT_PLACE] [nchar](255) NULL,
 CONSTRAINT [PK_EXPORT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[EXPORT] ON 
GO
INSERT [dbo].[EXPORT] ([ID], [EXPORT_NAME], [EXPORT_DATETIME], [EXPORT_USER], [EXPORT_PLACE]) VALUES (1, N'Date do raportu', CAST(N'2022-08-01T08:22:42.127' AS DateTime), N'Przemek', N'Bielsko-Bia³a')
GO
INSERT [dbo].[EXPORT] ([ID], [EXPORT_NAME], [EXPORT_DATETIME], [EXPORT_USER], [EXPORT_PLACE]) VALUES (3, N'Raport 2', CAST(N'2022-07-04T12:22:42.127' AS DateTime), N'Janusz', N'LódŸ')
GO
INSERT [dbo].[EXPORT] ([ID], [EXPORT_NAME], [EXPORT_DATETIME], [EXPORT_USER], [EXPORT_PLACE]) VALUES (4, N'Test raportu 100', CAST(N'2022-08-04T16:23:11.703' AS DateTime), N'Radek', N'Bielsko-Bia³a')
GO
INSERT [dbo].[EXPORT] ([ID], [EXPORT_NAME], [EXPORT_DATETIME], [EXPORT_USER], [EXPORT_PLACE]) VALUES (5, N'Raport nadrzêdny A', CAST(N'2022-07-29T16:23:11.703' AS DateTime), N'Przemek', N'Bielsko-Bia³a')
GO
INSERT [dbo].[EXPORT] ([ID], [EXPORT_NAME], [EXPORT_DATETIME], [EXPORT_USER], [EXPORT_PLACE]) VALUES (7, N'Raport 3', CAST(N'2022-06-04T12:22:42.127' AS DateTime), N'Radek', N'Warszawa')
GO
SET IDENTITY_INSERT [dbo].[EXPORT] OFF
GO
ALTER TABLE [dbo].[EXPORT] ADD  CONSTRAINT [DF_EXPORT_EXPORT_DATETIME]  DEFAULT (getdate()) FOR [EXPORT_DATETIME]
GO
USE [master]
GO
ALTER DATABASE [LSI_Export] SET  READ_WRITE 
GO
